### ISSUE TITLE
prepared data

### ISSUE THREAD

**Issue by zhang-jinyi** [tkengo/tf#1]
Hi,tkengo

I have read your blog from
http://tkengo.github.io/blog/2016/03/14/text-classification-by-cnn/
and i want to test the code,but i had a question below.
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    x, y, d = data_helper.load_data_and_labels_and_dictionaries()
  File "/home/dell/Downloads/tf-master/cnn_text_classification/data_helper.py", line 39, in load_data_and_labels_and_dictionaries
    contents = [ split_word(t, l[1]) for l in lines ]
IndexError: list index out of range

here is my raw.txt,just follow your blog's sentence.

1私は恋がしたいです。
2私は結婚を真剣に考えています。
3今の職場が嫌で早く転職をしたいです。
Can any help? Or tell me how to create your raw.txt (i don't your label' meaning)

Thanks.

**Comment by tkengo** [comment]
Thank you for reading my blog.

You need to insert the tab character `\t` between a category id and a sentence.
So your raw text should be following:

```
1\t私は恋がしたいです。
2\t私は結婚を真剣に考えています。
3\t今の職場が嫌で早く転職をしたいです。
```

Because the lines will be split by the tab character `\t` in [this line](https://github.com/tkengo/tf/blob/master/cnn_text_classification/data_helper.py#L36).
Could you try again after modifying your text?

**Comment by renzhe0009** [comment]
Thank you for replying me
I had trid after modified my text.
but still the same question below,

zhang@ubuntu:~/Downloads/tf-master/cnn_text_classification$ python train.py
Traceback (most recent call last):
  File "train.py", line 13, in <module>
    x, y, d = data_helper.load_data_and_labels_and_dictionaries()
  File "/home/zhang/Downloads/tf-master/cnn_text_classification/data_helper.py", line 41, in load_data_and_labels_and_dictionaries
    contents = [ split_word(t, l[1]) for l in lines ]
IndexError: list index out of range

And  I tried to find why in python,
zhang@ubuntu:~/Downloads/tf-master/cnn_text_classification$ python
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> lines = [ l.split("\t") for l in list(open('data/raw.txt').readlines()) ]
>>> print lines
[['1\\t\xe7\xa7\x81\xe3\x81\xaf\xe6\x81\x8b\xe3\x81\x8c\xe3\x81\x97\xe3\x81\x9f\xe3\x81\x84\xe3\x81\xa7\xe3\x81\x99\xe3\x80\x82\n'], ['2\\t\xe7\xa7\x81\xe3\x81\xaf\xe7\xb5\x90\xe5\xa9\x9a\xe3\x82\x92\xe7\x9c\x9f\xe5\x89\xa3\xe3\x81\xab\xe8\x80\x83\xe3\x81\x88\xe3\x81\xa6\xe3\x81\x84\xe3\x81\xbe\xe3\x81\x99\xe3\x80\x82\n'], ['3\\t\xe4\xbb\x8a\xe3\x81\xae\xe8\x81\xb7\xe5\xa0\xb4\xe3\x81\x8c\xe5\xab\x8c\xe3\x81\xa7\xe6\x97\xa9\xe3\x81\x8f\xe8\xbb\xa2\xe8\x81\xb7\xe3\x82\x92\xe3\x81\x97\xe3\x81\x9f\xe3\x81\x84\xe3\x81\xa7\xe3\x81\x99\xe3\x80\x82\n']]
>>> import MeCab
>>> t = MeCab.Tagger('-Owakati -d /usr/local/lib/mecab/dic/mecab-ipadic-neologd')
>>> word = t.parse(l[1]).split(' ')
>>> word = [ w.strip().decode('utf-8') for w in word ]
>>> 

It looks like that has something wrong with the font.
I don't konw why,but i think i have installed MeCab and neologd  successfully.
zhang@ubuntu:~/mecab-ipadic-neologd$ echo "10日放送の「中居正広のミになる図書館 」（テレビ朝日系）で、SMAPの中居正広が、篠原信一の過去の勘違いを明かす一幕があった。" | mecab -d /usr/local/lib/mecab/dic/mecab-ipadic-neologd
10日	名詞,固有名詞,一般,*,*,*,10日,ジュウニチ,ジュウニチ
放送	名詞,サ変接続,*,*,*,*,放送,ホウソウ,ホーソー
の	助詞,連体化,*,*,*,*,の,ノ,ノ
「	記号,括弧開,*,*,*,*,「,「,「
中居正広のミになる図書館	名詞,固有名詞,一般,*,*,*,中居正広のミになる図書館,ナカイマサヒロノミニナルトショカン,ナカイマサヒロノミニナルトショカン
」	記号,括弧閉,*,*,*,*,」,」,」
（	記号,括弧開,*,*,*,*,（,（,（
テレビ	名詞,固有名詞,一般,*,*,*,テレビ,テレビ,テレビ
朝日	名詞,固有名詞,組織,*,*,*,朝日,アサヒ,アサヒ
系	名詞,接尾,一般,*,*,*,系,ケイ,ケイ
）	記号,括弧閉,*,*,*,*,）,）,）
で	助詞,格助詞,一般,*,*,*,で,デ,デ
、	記号,読点,*,*,*,*,、,、,、
SMAP	名詞,固有名詞,一般,*,*,*,SMAP,スマップ,スマップ
の	助詞,連体化,*,*,*,*,の,ノ,ノ
中居正広	名詞,固有名詞,人名,一般,*,*,中居正広,ナカイマサヒロ,ナカイマサヒロ
が	助詞,格助詞,一般,*,*,*,が,ガ,ガ
、	記号,読点,*,*,*,*,、,、,、
篠原信一	名詞,固有名詞,人名,一般,*,*,篠原信一,シノハラシンイチ,シノハラシンイチ
の	助詞,連体化,*,*,*,*,の,ノ,ノ
過去	名詞,副詞可能,*,*,*,*,過去,カコ,カコ
の	助詞,連体化,*,*,*,*,の,ノ,ノ
勘違い	名詞,サ変接続,*,*,*,*,勘違い,カンチガイ,カンチガイ
を	助詞,格助詞,一般,*,*,*,を,ヲ,ヲ
明かす	動詞,自立,*,*,五段・サ行,基本形,明かす,アカス,アカス
一幕	名詞,一般,*,*,*,*,一幕,ヒトマク,ヒトマク
が	助詞,格助詞,一般,*,*,*,が,ガ,ガ
あっ	動詞,自立,*,*,五段・ラ行,連用タ接続,ある,アッ,アッ
た	助動詞,*,*,*,特殊・タ,基本形,た,タ,タ
。	記号,句点,*,*,*,*,。,。,。
EOS

Thank you very much.

**Comment by zhang-jinyi** [comment]
I changed the code below,
from
lines = [ l.split("\t") for l in list(open('data/raw.txt').readlines()) ]
to
lines = open ('data/raw.txt','r')
so the data_helper.py doesn't get wrong.
but ,anyway,

ValueError: Filter must not be larger than the input: Filter: (3, 128) Input: (2, 128)

so I changed the FILTER_SIZES      = [ 3,4,5 ] to[2]
this time the result is,

Traceback (most recent call last):
  File "train.py", line 118, in <module>
    feed_dict={ input_x: mini_batch_x, input_y: mini_batch_y, keep: 0.5 }
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 372, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 625, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (0,) for Tensor u'Placeholder_1:0', which has shape '(?, 2)'

Still something wrong with the font. I think.
Forward to your reply!

**Comment by zhang-jinyi** [comment]
SORRY!
@tkengo 
I think I find my mistakes. Tab key ,not ' \t' 
I created raw.txt as follows,

1   私は恋がしたいです。
1   私は結婚を真剣に考えています。
2   今の職場が嫌で早く転職をしたいです。
1   彼女の事を好きになってしまいました。
1   次の日からメッセージを送っても未読のまま無視される様になり、嫌われるのが嫌だった
1   電話は切られ、連絡が取れずに現在に至ります。
1   片思い、告白、初めての彼氏・彼女、デートのことなど恋愛に関して聞きたいこと
1   同じクラスの男子に恋をしています。
1   友達に恋をしています。
1   私が好きだ
2   私のミスが面白くて仕方ないんだと思います。
2   私は組んだ事がないのですが、組んだ人は２倍の仕事をしてる
2   環境…確かに悪いです。
2   長年勤めた職場に退職願いを申し出た結果、後任の指導料として特別報酬がでることになりました。
2   口頭では辞退を申し出ました
2   最近になってよく嫌われるようになった気がする
1   15才上の先生を好きになりました。
1   先生が気づいているか分かりません。
1   俺の事が嫌いになったのかと思ったと言われました。

So that I just created 'love' and 'work' two labels and 20 sentiments.
(Plz do not laugh at my Japanese ^.^)
changed the value: NUM_CLASSES       = 2
At last, data_helper.py goes well,no problem.
But...

zhang@ubuntu:~/Downloads/tf-master/cnn_text_classification$ python train.py
WARNING:tensorflow:Passing a `GraphDef` to the SummaryWriter is deprecated. Pass a `Graph` object instead, such as `sess.graph`.
2016/10/28 01:34:18: Start training.
2016/10/28 01:34:18:      epoch: 10
2016/10/28 01:34:18: mini batch: 64
2016/10/28 01:34:18: train data: 0
2016/10/28 01:34:18:  test data: 19
2016/10/28 01:34:18: We will loop 1 count per an epoch.
2016/10/28 01:34:18: Start 1th epoch.
Traceback (most recent call last):
  File "train.py", line 118, in <module>
    feed_dict={ input_x: mini_batch_x, input_y: mini_batch_y, keep: 0.5 }
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 372, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 625, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (0,) for Tensor u'Placeholder_1:0', which has shape '(?, 28)'

2016/10/28 01:34:18: train data: 0 , It means train_x =0. 
My prepared data didn't worded…… I am confused, maybe the data-font's fault.
Could you creat a test-raw.txt and show me ?

Forward to your reply!

**Comment by tkengo** [comment]
hi @renzhe0009. I'm sorry to reply late.

I guess `NUM_TESTS` constant value is too large. The constant value is defined in `constants.py` and it is `2000`.

This program splits your data into training data and testing data.
Now there are 19 sample data as your data loaded from `raw.txt`, so all of your data will become test data, then training data is nothing.

Could you change the value of `NUM_TESTS` and try it again?

**Comment by zhang-jinyi** [comment]
@tkengo 
Thank you for your patience.
Now,it works well.
Hope this will help me to learn tensorflow well.
Plz close this issue

**Comment by tkengo** [comment]
That's good to know. Good luck 😃
